resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:dcd6875f5e01fc642c029ce17df2f85b1b5182b459bfb2062b7838420c566de6
  name: quay.io/rhdevelopers/quinoa-wind-turbine
