resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3b85c4a20eba964702d1a94dc41625e10d8003f4c8ed250e12f4160f7f65513c
  name: quay.io/rhdevelopers/quinoa-wind-turbine
