resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b9801a4d9edfdc3674dd660171d8a5399717186683cd384637b38f7882fe4c7c
  name: quay.io/rhdevelopers/quinoa-wind-turbine
