resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3b6bc267f691e95e9c696c8ff6e69c9018e383f020751ea2bf7564f1b908f48b
  name: quay.io/rhdevelopers/quinoa-wind-turbine
