resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:ffe1ff8a8096f8dc40427a331a7bd450ff5dc9bd63375381cfded310b552ca86
  name: quay.io/rhdevelopers/quinoa-wind-turbine
