resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e69ce18076b5478387dd9d87a29f8e995d3fd9be75ddd12a30fd112e7750c0e3
  name: quay.io/rhdevelopers/quinoa-wind-turbine
