resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:5fc1bbe5186e938e16fddd6b4068bf049020ad00f262f82a77f87cc2e9a5a52a
  name: quay.io/rhdevelopers/quinoa-wind-turbine
