resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3135920f9e132a72032188875520dc831f526a18ead84d01b5d03b1f3f14a229
  name: quay.io/rhdevelopers/quinoa-wind-turbine
