resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:0fccc73dcee0241405ae76b320a923a9ba923f724d9d51691963dc20f3f43c74
  name: quay.io/rhdevelopers/quinoa-wind-turbine
