resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:910fff9a30d03fbda22f309d387212f173cd7e9449f20d274e5a3fb4bb2c6430
  name: quay.io/rhdevelopers/quinoa-wind-turbine
