resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3b51a42e19b5e1b0ba39d6827530f4bc0e59fcd19b3a5146830174522a34c1c2
  name: quay.io/rhdevelopers/quinoa-wind-turbine
