resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:2372f384f9c191dc985051becc9d3cd7d8450d81aee56050e6c94a55d4661333
  name: quay.io/rhdevelopers/quinoa-wind-turbine
