resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:063ad9f040ec7fec2887caf7006b377a0b82cd0756ca8406e4629695039e5450
  name: quay.io/burrsutter/quinoa-wind-turbine
- digest: sha256:45ab95664404dcde320003f751ee1e326f869e5a69eed4bc3f2efea0ee69f3b8
  name: quay.io/rhdevelopers/quinoa-wind-turbine
