resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:d284b77e4468d147865155b3fe796578effe83b5b747f97c3c73e4de27ec1e4e
  name: quay.io/rhdevelopers/quinoa-wind-turbine
