resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:a5d99734beb2d034516bcd98736155ac2ede60b13b8ad595608ca3b7ac343c19
  name: quay.io/rhdevelopers/quinoa-wind-turbine
