resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:5830b05e35bb7bd3d021b4dcb1df6ce4cac43c4705b31cb07b953cc74b218335
  name: quay.io/rhdevelopers/quinoa-wind-turbine
