resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:073a14460294783edd17991b89be55823f0a47c0e6437342eb1837715fa0ffa6
  name: quay.io/rhdevelopers/quinoa-wind-turbine
