resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:6535a7bb156b79ed41cb8713b07837892a0c084ed0119729366160bff371ab34
  name: quay.io/rhdevelopers/quinoa-wind-turbine
