resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:cf899e5abdecfaf91a540359d5c183d77383742dce6ee5e6b0d4af3ed1d3ee14
  name: quay.io/rhdevelopers/quinoa-wind-turbine
