resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:34a9ec5f44bf693e903554bc9bd7b03ebf160bc4d28d653d1992e7d02e4c3726
  name: quay.io/rhdevelopers/quinoa-wind-turbine
