resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:d5de92b090070d80129e056869b2bd1a52505b73fa7f296c76f994a8bf79ab35
  name: quay.io/rhdevelopers/quinoa-wind-turbine
