resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:65f0680b2fef6a8608ea20b931a23998a267d76aea884a9a5d67aa9fcb19cf1b
  name: quay.io/rhdevelopers/quinoa-wind-turbine
