resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:c7f099161b5dd145f0940c2fcc8abab00dd536087246f7127822600bef022da3
  name: quay.io/rhdevelopers/quinoa-wind-turbine
