resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:81f400e24c17c1964353d3bd9b1e1372384dc6e4bf952c0c32546717f74ccaca
  name: quay.io/rhdevelopers/quinoa-wind-turbine
