resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:8a4954bd41dfb2a3c6e8a8258404b08adea0d2c36fc7935ebefc75c4c03f50a6
  name: quay.io/rhdevelopers/quinoa-wind-turbine
