resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:dc2b370d5187623810caf5b031f9233721deb88edcd4515984a74ccdf414e63a
  name: quay.io/rhdevelopers/quinoa-wind-turbine
