resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:fe8d491dd95c26b3658144a8538a8c98c75085aa07f70f3be09cad78047fc4b6
  name: quay.io/rhdevelopers/quinoa-wind-turbine
