resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:8d6d024e472d9570f68ef5d05051c49d67714fbb95207fe98f759138ae1f3325
  name: quay.io/rhdevelopers/quinoa-wind-turbine
