resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:88ae97d578c5529dfa2d0a369f7fc323e1571c3c061dbe7b7a341878810c5757
  name: quay.io/rhdevelopers/quinoa-wind-turbine
