resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:613641dfd534a39cd0ba9cc21c95b40e12ba368350aca75b629df5fafe9a4cc8
  name: quay.io/rhdevelopers/quinoa-wind-turbine
