resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:51693ac95fd1e81147f465bad7ae2176fe50898dedde10df2f050d3a49ce589a
  name: quay.io/rhdevelopers/quinoa-wind-turbine
