resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:063ad9f040ec7fec2887caf7006b377a0b82cd0756ca8406e4629695039e5450
  name: quay.io/burrsutter/quinoa-wind-turbine
- digest: sha256:98e5dfae2e76d85152258f0807e4f4fb76d35c1c9b330b00011652ec1a0d9b8e
  name: quay.io/rhdevelopers/quinoa-wind-turbine
